// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://owyshhuawqnkcmmfdtmm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im93eXNoaHVhd3Fua2NtbWZkdG1tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwNDQ3NzcsImV4cCI6MjA2NDYyMDc3N30.gDAPlucCuoFFsjfloxE-te1B-IwMKW8XXLlDJyDh45I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);